
Watching for file changes with StatReloader
index page accessed
"GET / HTTP/1.1" 200 479
about page accessed
"GET /about/ HTTP/1.1" 200 464
index page accessed
"GET / HTTP/1.1" 200 479
about page accessed
"GET /about/ HTTP/1.1" 200 464
index page accessed
"GET / HTTP/1.1" 200 479
Watching for file changes with StatReloader
index page accessed
"GET / HTTP/1.1" 200 680
about page accessed
"GET /about/ HTTP/1.1" 200 672
index page accessed
"GET / HTTP/1.1" 200 680
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_2\project\myapp2\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2227
Not Found: /
"GET / HTTP/1.1" 404 2227
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2278
Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\http\response.py", line 134, in __init__
    self.status_code = int(status)
                       ^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return HttpResponse(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\http\response.py", line 374, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\http\response.py", line 136, in __init__
    raise TypeError("HTTP status code must be an integer.")
TypeError: HTTP status code must be an integer.
"GET /index/ HTTP/1.1" 500 76534
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp2/base.html
"GET /index/ HTTP/1.1" 500 77485
Watching for file changes with StatReloader
Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp2/base.html
"GET /index/ HTTP/1.1" 500 77485
Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp2/base.html
"GET /index/ HTTP/1.1" 500 77485
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp2/base.html
"GET / HTTP/1.1" 500 77276
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp2/base.html
"GET / HTTP/1.1" 500 77414
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/base.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp2/base.html
"GET / HTTP/1.1" 500 77414
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
"GET / HTTP/1.1" 500 62661
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 248
"GET /hello HTTP/1.1" 301 0
Internal Server Error: /hello/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view myapp2.views.hello didn't return an HttpResponse object. It returned None instead.
"GET /hello/ HTTP/1.1" 500 64055
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hello/ HTTP/1.1" 200 5
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 259
"GET / HTTP/1.1" 200 259
"GET / HTTP/1.1" 200 259
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 12, in index
    return render(request, "myapp2/index.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET / HTTP/1.1" 500 123583
"GET / HTTP/1.1" 200 234
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 234
"GET /user/1 HTTP/1.1" 301 0
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: users_order() got an unexpected keyword argument 'user_id'
"GET /user/1/ HTTP/1.1" 500 59675
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2663
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 18, in users_order
    order = Order.objects.filter(user=user).order_by('-date')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, date, id, products, total_price
"GET /user/1/ HTTP/1.1" 500 109036
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    return render(request, 'myapp2/list_order.html', {'user':user, 'order':order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 14: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET /user/1/ HTTP/1.1" 500 179144
"GET /user/1/ HTTP/1.1" 200 263
"GET /user/1/ HTTP/1.1" 200 263
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 264
"GET /user/1/ HTTP/1.1" 200 264
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
"GET /user/1/ HTTP/1.1" 200 263
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 393
"GET /user/1/ HTTP/1.1" 200 395
"GET /user/2/ HTTP/1.1" 200 399
"GET /user/3/ HTTP/1.1" 200 397
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /user/3/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Product.objects.filter(order_id=orders).order_by('-date')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order_id' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/3/ HTTP/1.1" 500 110775
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/3/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Product.objects.filter(products=user).order_by('-date')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'products' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/3/ HTTP/1.1" 500 110263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/3/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Product.objects.filter(order_id=user).order_by('-date')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order_id' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/3/ HTTP/1.1" 500 110263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/3/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Order.objects.filter(order_id=user).order_by('-date')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order_id' into field. Choices are: customer, customer_id, date, id, products, total_price
"GET /user/3/ HTTP/1.1" 500 109416
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/3/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Order.objects.filter(products=user).order_by('-date')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1532, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1346, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1323, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "Username: Emi": Must be "Product" instance.
"GET /user/3/ HTTP/1.1" 500 110516
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/3/ HTTP/1.1" 200 325
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/3/ HTTP/1.1" 200 325
"GET /user/1/ HTTP/1.1" 200 323
"GET /user/1/ HTTP/1.1" 200 323
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Order.objects.filter(products=user).order_by('-date')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1532, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1346, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1323, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "Username: Vi": Must be "Product" instance.
"GET /user/1/ HTTP/1.1" 500 110500
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
Watching for file changes with StatReloader
"GET /user/2/ HTTP/1.1" 200 267
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 393
Internal Server Error: /product/1
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 23, in products
    return render(request, 'myapp2/list_products.html', {'product':product})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'endfor', expected 'endblock'. Did you forget to register or load this tag?
"GET /product/1 HTTP/1.1" 500 162189
"GET /product/1 HTTP/1.1" 200 286
"GET /product/1 HTTP/1.1" 200 291
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: users_order() missing 1 required positional argument: 'product_id'
"GET /user/1/ HTTP/1.1" 500 59711
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 328
"GET /user/1/ HTTP/1.1" 200 342
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 500
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 342
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 658
"GET /user/1/ HTTP/1.1" 200 588
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Product.objects.filter(product_id=orders)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'product_id' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 110789
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    product = Product.objects.filter(product_id=orders)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'product_id' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 110789
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 393
"GET /user/1/ HTTP/1.1" 200 393
"GET /user/1/ HTTP/1.1" 200 393
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/2/ HTTP/1.1" 200 529
"GET /user/3/ HTTP/1.1" 200 532
"GET /user/2/ HTTP/1.1" 200 529
"GET /user/1/ HTTP/1.1" 200 526
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 18, in users_order
    products = Product.objects.filter(order__customer=user).filter(datetime__month=1).distinct()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'datetime' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 104682
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    products = Product.objects.filter(order__customer=user).filter(datetime__month=1).distinct()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'datetime' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 104682
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    products = Product.objects.filter(order__customer=user, datetime__month=2).distinct()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'datetime' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 110288
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    products = Product.objects.filter(order__customer=user, datetime__month=1).distinct()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'datetime' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 110288
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    products = Product.objects.filter(order__customer=user).distinct().order_by('month')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1701, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 2253, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'month' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 79250
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 19, in users_order
    products = Product.objects.filter(datetime__month=5).distinct().order_by('-date')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'datetime' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 109910
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 395
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 395
"GET /user/1/ HTTP/1.1" 200 395
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 461
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 461
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 394
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 328
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 395
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py", line 25, in users_order
    products = Product.objects.filter(order__customer=user, product__date__gte=last_week).distinct().order_by('-date')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'product' into field. Choices are: date, description, id, name, order, price, quantity
"GET /user/1/ HTTP/1.1" 500 112168
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 263
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/2/ HTTP/1.1" 200 529
"GET /user/3/ HTTP/1.1" 200 532
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 526
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 394
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 395
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_3\project\myapp2\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user/1/ HTTP/1.1" 200 1071
"GET /user/1/ HTTP/1.1" 200 1264
"GET /user/2/ HTTP/1.1" 200 1264
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5944
"GET /admin/auth/user/add/ HTTP/1.1" 200 11238
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 23739
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 12659
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/add/ HTTP/1.1" 200 12858
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 9536
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/ HTTP/1.1" 200 12747
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 23534
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 12971
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 8141
"POST /admin/logout/ HTTP/1.1" 200 3817
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5447
"GET /admin/myapp2/product/ HTTP/1.1" 200 8486
"GET /admin/myapp2/product/add/ HTTP/1.1" 200 9777
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 8486
"GET /admin/myapp2/product/12/change/ HTTP/1.1" 200 9951
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 8486
"GET /admin/myapp2/product/3/change/ HTTP/1.1" 200 9957
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 8486
"GET /admin/myapp2/product/ HTTP/1.1" 200 8486
"GET /admin/myapp2/product/ HTTP/1.1" 200 8486
"GET /admin/myapp2/product/12/change/ HTTP/1.1" 200 9951
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"POST /admin/logout/ HTTP/1.1" 200 3817
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 8141
"GET /admin/myapp2/product/ HTTP/1.1" 200 13273
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/ HTTP/1.1" 200 9863
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/1/change/ HTTP/1.1" 200 13676
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/auth/group/ HTTP/1.1" 200 9863
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 13273
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /admin/myapp2/product/ HTTP/1.1" 200 15705
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/myapp2/product/ HTTP/1.1" 200 16013
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=-1 HTTP/1.1" 200 16368
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=1 HTTP/1.1" 200 16351
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=2.1 HTTP/1.1" 200 16863
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=-2.1 HTTP/1.1" 200 16882
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=2.1 HTTP/1.1" 200 16863
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=-2.1 HTTP/1.1" 200 16882
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o=1 HTTP/1.1" 200 16351
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/?o= HTTP/1.1" 200 16030
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/myapp2/product/?o= HTTP/1.1" 200 14983
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/user/ HTTP/1.1" 200 11204
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 14962
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/user/ HTTP/1.1" 200 11204
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 14962
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/user/ HTTP/1.1" 200 11204
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 14962
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/user/ HTTP/1.1" 200 11204
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Desktop\GB\Django\lesson_5\project\myapp2\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/myapp2/user/ HTTP/1.1" 200 11199
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/order/ HTTP/1.1" 200 12134
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 15261
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/user/ HTTP/1.1" 200 11199
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/order/ HTTP/1.1" 200 12134
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/product/ HTTP/1.1" 200 15261
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
"GET /admin/myapp2/user/ HTTP/1.1" 200 11199
"GET /admin/jsi18n/ HTTP/1.1" 200 17546
